import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NextAuthSessionProviders from "@/Providers/NextAuthSessionProviders";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-primary overflow-x-hidden">
      <NextAuthSessionProviders>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased mx-auto
        max-w-[350px] md:max-w-2xl lg:max-w-4xl xl:max-w-6xl 2xl:max-w-screen-2xl
        `} //set up width
        >
          {/* <Header /> */}
          <header className="fixed inset-x-0 top-0 z-50 bg-secondary">
            <Navbar />
          </header>
          <main className="">
            {children}
          </main>
            <Footer />
          
        </body>
      </NextAuthSessionProviders>
    </html>
  );
}
